image:
  name: docker:git
  entrypoint: ['']

services:
  - name: docker:dind
    alias: thedockerhost

variables:
  # Tell docker CLI how to talk to Docker daemon; see
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
  DOCKER_HOST: tcp://thedockerhost:2375/
  # Use the overlayfs driver for improved performance:
  # DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

before_script:
  - export TAG=$([ $CI_COMMIT_BRANCH == "master" ] && echo "prod" || echo "test" )
  - export NUXT_PUBLIC_SHOW_COMPONENTS_PAGE=$([ $CI_COMMIT_BRANCH == "master" ] && echo "off" || echo "on" )
  - export VERSION=$CI_COMMIT_SHORT_SHA
  - export STRAPI_URL=$([ $CI_COMMIT_BRANCH == "master" ] && echo "$STRAPI_URL" || echo "$STRAPI_TEST_URL" )
  - export NUXT_PUBLIC_OPEN_AI_KEY=$([ $CI_COMMIT_BRANCH == "master" ] && echo "$NUXT_PUBLIC_OPEN_AI_KEY" || echo "$NUXT_PUBLIC_OPEN_AI_KEY_TEST" )
  - export NUXT_PUBLIC_MATOMO_APP_ID=$([ $CI_COMMIT_BRANCH == "master" ] && echo "$NUXT_PUBLIC_MATOMO_APP_ID" || echo "$NUXT_PUBLIC_MATOMO_APP_ID_TEST" )
  - if [ -d "${CI_PROJECT_DIR}" ]; then rm -rf "${CI_PROJECT_DIR}"; fi
  - mkdir -p "${CI_PROJECT_DIR}"
  - cd "${CI_PROJECT_DIR}"
  - git init
  - git remote add origin "https://gitlab+deploy-token-2:$DEPLOY_TOKEN@gitlab.profbrenojac.com.br/${CI_PROJECT_PATH}.git"
  - git fetch origin "${CI_COMMIT_SHA}"
  - git reset --hard FETCH_HEAD

stages: # List of stages for jobs, and their order of execution
  - build
  - vercel
  # - deploy
  #- test

build-app2: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t "projetoalex/alex-app:v2-$TAG" --build-arg matomo_url="$NUXT_PUBLIC_MATOMO_URL" --build-arg matomo_app_id=$NUXT_PUBLIC_MATOMO_APP_ID --build-arg strapi_url=$STRAPI_URL --build-arg components_page=$NUXT_PUBLIC_SHOW_COMPONENTS_PAGE --build-arg open_ai_key="$NUXT_PUBLIC_OPEN_AI_KEY" -f Dockerfile  .
    - docker push "projetoalex/alex-app:v2-$TAG"
  only:
    - master
    - test

# deploy:
#   stage: deploy
#   image:
#     name: bitnami/kubectl:1.26.4
#     entrypoint: ['']
#   script:
#     - kubectl config use-context projeto-alex/app-alex:app-alex-agent
#     - sed s/%VERSION%/$VERSION/g "kubernetes/alex-app2-$TAG.yaml" > deploy-alex-app2.yaml
#     - kubectl apply --validate=false -f deploy-alex-app2.yaml -v=8
#   only:
#     - master
#     - test

deploy_vercel:
  stage: vercel
  image: node:20
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - NITRO_PRESET=vercel vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN
  only:
    - merge_requests
