apiVersion: v1
kind: Service
metadata:
  name: alex-app2-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: alex-app2-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-app2-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alex-app2-test
  template:
    metadata:
      labels:
        app: alex-app2-test
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: node
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: alex-app2-test
      imagePullSecrets:
        - name: regcred
      containers:
        - name: alex-app2-test
          imagePullPolicy: Always
          image: projetoalex/alex-app:v2-test%VERSION%
          ports:
            - containerPort: 3000
          env:
            - name: STRAPI_URL
              value: https://api-v4-test.projetoalex.cc
